MONGODB_HOST: mongodb-{{ env }}.kolanu.space
REDIS_HOST: redis-{{ env }}.kolanu.space
CATALOGUE_HOST: catalogue-{{ env }}.kolanu.space
USER_HOST: user-{{ env }}.kolanu.space
MYSQL_HOST: mysql-{{ env }}.kolanu.space
CART_HOST: cart-{{ env }}.kolanu.space
SHIPPING_HOST: shipping-{{ env }}.kolanu.space
PAYMENT_HOST: payment-{{ env }}.kolanu.space
RABBITMQ_HOST: rabbitmq-{{ env }}.kolanu.space
