MONGODB_HOST: mongodb-{{ env }}.kolanu.space
REDIS_HOST: redis-{{ env }}.kolanu.space
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.kolanu.space
USER_HOST: user.backend-alb-{{ env }}.kolanu.space
MYSQL_HOST: mysql-{{ env }}.kolanu.space
CART_HOST: cart.backend-alb-{{ env }}.kolanu.space
SHIPPING_HOST: shipping.backend-alb-{{ env }}.kolanu.space
PAYMENT_HOST: payment.backend-alb-{{ env }}.kolanu.space
RABBITMQ_HOST: rabbitmq-{{ env }}.kolanu.space
